Fix develop branch CI builds (#133)
* Change Dependabot to target develop

it hasn't been working yet because the file hasn't made it into
the default branch (main)

* Update Actions versions

* Set $SPACK_STACK_DIR

* Clone JCSDA spack current release

* cleanup

* Fetch ESMF in old CI and re-enable

* Disable GFortran 12

Got this in the run:

/home/runner/work/CATChem/CATChem/src/core/ProcessFactory_Mod.F90:77:52:

   77 |       met_fields = process%get_required_met_fields()
      |                                                    1
internal compiler error: Segmentation fault
0x1a6a04a internal_error(char const*, ...)
	???:0
0x9af8bc fold_convert_loc(unsigned int, tree_node*, tree_node*)
	???:0
0x7a064b gfc_trans_create_temp_array(stmtblock_t*, stmtblock_t*, gfc_ss*, tree_node*, tree_node*, bool, bool, bool, locus*)
	???:0
0x7d1819 gfc_conv_procedure_call(gfc_se*, gfc_symbol*, gfc_actual_arglist*, gfc_expr*, vec<tree_node*, va_gc, vl_embed>*)
	???:0
0x7ab409 gfc_conv_loop_setup(gfc_loopinfo*, locus*)
	???:0
0x7c6d49 gfc_generate_function_code(gfc_namespace*)
	???:0
0x79cef9 gfc_generate_module_code(gfc_namespace*)
	???:0
0x73e59d gfc_parse_file()
	???:0

* Use earlier JCSDA spack, don't run on every push

* Try build NUOPC on in non-spack-stack CI

We need MPI (mpiuni ESMF isn't sufficient)

[ 95%] Building Fortran object drivers/nuopc/CMakeFiles/NUOPC_CATChem_cap.dir/catchem_nuopc_interface.F90.o
/home/runner/work/CATChem/CATChem/drivers/nuopc/catchem_nuopc_interface.F90:30:8:

   30 |    use MPI
      |        1
Fatal Error: Cannot open module file ‘mpi.mod’ for reading at (1): No such file or directory
compilation terminated.

* Ensure C compiler versions match

Saw this in the GFortran 14 run:

FC: mpifort
OMPI_FC: gfortran-14
-- The Fortran compiler identification is GNU 14.2.0
-- The C compiler identification is GNU 13.3.0

but also gha-esmf only build ESMF with GFortran 13 currently,
so let's do that version only
but we can include a non-ESMF variant, with BUILD_NUOPC=OFF

* Add BUILD_NUOPC=OFF cases

* Add a job using jcsda/docker-gnu-openmpi-dev:1.9

* cleanup

* More cleanup

GCC 13 (including Fortran) is already present on ubuntu-24.04

spack-stack CI uses MPICH, not OpenMPI